name: Fontid Action

on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'docs/*'
      - 'README.md'
      - '*/README.md'
      - 'LICENSE'

jobs:
  fontid-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Copy files
        run: |
          mkdir 'docker/app'
          cp 'src/server.py' 'docker/app/server.py'
          cp 'src/requirements.txt' 'docker/requirements.txt'

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: 'docker'
          repository: unbinilium/font-identifier-rest-api
          tags: latest
